### ISSUE TITLE
[Enhancement] APT Repository for rlchroot packages

### ISSUE THREAD

**Issue by WMCB-Tech** [WMCB-Tech/rlchroot#8]

**Comment by LeapofAzzam-backup** [comment]
I tried to add your package (includes debdroid) with termux-apt-repo but it fails
![Screenshot_20210126-115930](https://user-images.githubusercontent.com/76893443/105802634-2b57ad00-5fce-11eb-9a7f-230af72e28d3.png)

**Comment by WMCB-Tech** [comment]
Next update should fix the Architecture naming, mine says Architecture "all" not supported

**Comment by LeapofAzzam-backup** [comment]
> mine says Architecture "all" not supported

Actually mine too so i edited the script which is basically a python program

**Comment by WMCB-Tech** [comment]
I should be able to merge the `enter-rootfs` code as users can run custom linux distros without needing a template configuration, and a bonus of standard `lxc` commands including:

`lxc file push`
`lxc publish`

Something like that

**Comment by WMCB-Tech** [comment]
It turns out that the Architecture section has spacing on it
```
Architecture=all <space>
```

I couldn't edit the debian package in the current version, but in the next release should be fixed

**Comment by LeapofAzzam-backup** [comment]
That's why it failed

Pada tanggal Sel, 26 Jan 2021 1.41 PM, marcusz <notifications@github.com>
menulis:

**Comment by WMCB-Tech** [comment]
I think it can be hosted with my github pages repository (Tested it with apache web server and local file uri in apt)

![Screenshot_2021-01-26-15-01-28-41.jpg](https://user-images.githubusercontent.com/65075766/105811431-896f9a80-5fa4-11eb-9b8e-9d80e625dced.jpg)

**Comment by WMCB-Tech** [comment]
Ok, i created a repo, so to install rlchroot via apt, simply do:
`echo "deb https://wmcb-tech.github.io/files termux universe" > $PREFIX/etc/apt/sources.list.d/rlchroot.list`
`pkg in rlchroot`
